name: Karotz TTS
version: "1.0.0"
slug: karotz-tts
description: TTS local pour Karotz. Optimisé pour Raspberry Pi 3 B+ et versions ultérieures.
url: https://github.com/Desperado88/karotz-tts-addon
startup: services
boot: auto
hassio_api: false
host_network: true
homeassistant_api: false
options: {}
schema: {}
icon: icon.png
arch:
  - amd64
  - aarch64
  - armv7
  - armhf

