name: Karotz TTS (Pico)
version: "1.0.0"
slug: karotz_tts_pico
description: TTS local pour Karotz utilisant Pico TTS (Raspberry Pi 3/4)
startup: services
boot: auto
hassio_api: true
host_network: true
homeassistant_api: true
options:
  port: 5000
schema:
  port: int
icon: icon.png
image: "karotz-tts-pico"
arch:
  - aarch64
  - armv7
  - armhf
  - amd64
