name: Karotz TTS (Piper)
version: "1.0.0"
slug: karotz_tts_piper
description: TTS local pour Karotz utilisant Piper TTS (Raspberry Pi 5)
startup: services
boot: auto
hassio_api: true
host_network: true
homeassistant_api: true
options:
  port: 5000
schema:
  port: int
icon: icon.png
image: "karotz-tts-piper"
arch:
  - aarch64
  - armv7
  - armhf
  - amd64 
