name: Karotz piper TTS
version: "1.0.3"
slug: karotz-tts-piper
description: TTTS local pour Karotz utilisant Piper TTS (Raspberry Pi 4/5)
url: https://github.com/Desperado88/karotz-tts-addon-rpi/tree/main
startup: services
boot: auto
hassio_api: false
host_network: true
homeassistant_api: false
options: {}
schema: {}
icon: icon.png
arch:
  - amd64
  - aarch64
  - armv7
  - armhf
