name: Karotz TTS
version: "1.0.0"
slug: karotz-tts-piper
description: TTTS local pour Karotz utilisant Piper TTS (Raspberry Pi 4/5)
url: https://github.com/Desperado88/karotz-tts-addon
startup: services
boot: auto
hassio_api: false
host_network: true
homeassistant_api: false
options:
  model_name: fr_FR-upmc-medium
  sample_rate: 22050
schema:
  model_name:
    name: Nom du modèle
    description: Nom du modèle de voix à utiliser
    type: string
    default: fr_FR-upmc-medium
  sample_rate:
    name: Taux d'échantillonnage
    description: Taux d'échantillonnage audio (Hz)
    type: integer
    default: 22050
icon: icon.png
arch:
  - amd64
  - aarch64
  - armv7
  - armhf
